export const durations = [
    { value: "", label: "--- Duration ---" },
    { value: "1 Semester", label: "1 Semester" },
    { value: "1 month", label: "1 month" },
    { value: "10 Semesters", label: "10 Semesters" },
    { value: "10 Trimesters", label: "10 Trimesters" },
    { value: "10 months", label: "10 months" },
    { value: "11 Semesters", label: "11 Semesters" },
    { value: "11 Trimesters", label: "11 Trimesters" },
    { value: "12 Semesters", label: "12 Semesters" },
    { value: "12 Trimesters", label: "12 Trimesters" },
    { value: "12 months", label: "12 months" },
    { value: "13 Semesters", label: "13 Semesters" },
    { value: "13 Trimesters", label: "13 Trimesters" },
    { value: "13 months", label: "13 months" },
    { value: "14 Semesters", label: "14 Semesters" },
    { value: "14 Trimesters", label: "14 Trimesters" },
    { value: "15 months", label: "15 months" },
    { value: "16 months", label: "16 months" },
    { value: "17 months", label: "17 months" },
    { value: "18 months", label: "18 months" },
    { value: "2 Quarters", label: "2 Quarters" },
    { value: "2 Semesters", label: "2 Semesters" },
    { value: "2 months", label: "2 months" },
    { value: "20 Semesters", label: "20 Semesters" },
    { value: "20 months", label: "20 months" },
    { value: "21 months", label: "21 months" },
    { value: "24 months", label: "24 months" },
    { value: "27 months", label: "27 months" },
    { value: "29 months", label: "29 months" },
    { value: "3 Semesters", label: "3 Semesters" },
    { value: "3 Trimesters", label: "3 Trimesters" },
    { value: "3 Years", label: "3 Years" },
    { value: "30 months", label: "30 months" },
    { value: "31 months", label: "31 months" },
    { value: "32 months", label: "32 months" },
    { value: "33 months", label: "33 months" },
    { value: "36 months", label: "36 months" },
    { value: "4 Semesters", label: "4 Semesters" },
    { value: "4 Trimesters", label: "4 Trimesters" },
    { value: "4 Years", label: "4 Years" },
    { value: "41 months", label: "41 months" },
    { value: "42 months", label: "42 months" },
    { value: "48 months", label: "48 months" },
    { value: "5 Semesters", label: "5 Semesters" },
    { value: "5 Trimesters", label: "5 Trimesters" },
    { value: "56 months", label: "56 months" },
    { value: "6 Quarters", label: "6 Quarters" },
    { value: "6 Semesters", label: "6 Semesters" },
    { value: "6 Trimesters", label: "6 Trimesters" },
    { value: "7 Quarters", label: "7 Quarters" },
    { value: "7 Semesters", label: "7 Semesters" },
    { value: "7 Trimesters", label: "7 Trimesters" },
    { value: "8 Semesters", label: "8 Semesters" },
    { value: "9 Quarters", label: "9 Quarters" },
    { value: "9 Semesters", label: "9 Semesters" },
    { value: "9 Trimesters", label: "9 Trimesters" },
    { value: "N/A", label: "N/A" }
];

export const semesterStarts = [
    { value: "", label: "-- Beginning Semester --" },
    { value: "All Quarters", label: "All Quarters" },
    { value: "All Trimesters", label: "All Trimesters" },
    { value: "Autumn Quarter", label: "Autumn Quarter" },
    { value: "January", label: "January" },
    { value: "N/A", label: "N/A" },
    { value: "Other", label: "Other" },
    { value: "Spring", label: "Spring" },
    { value: "Spring Quarter", label: "Spring Quarter" },
    { value: "Spring Trimester", label: "Spring Trimester" },
    { value: "Summer", label: "Summer" },
    { value: "Summer Quarter", label: "Summer Quarter" },
    { value: "Winter", label: "Winter" },
    { value: "Winter Quarter", label: "Winter Quarter" },
    { value: "Winter Trimester", label: "Winter Trimester" }
];


export const teachingLanguages = [
    { value: "", label: "-- Teaching Language --" },
    { value: "Arabic", label: "Arabic" },
    { value: "Chinese", label: "Chinese" },
    { value: "Danish", label: "Danish" },
    { value: "English", label: "English" },
    { value: "Finnish", label: "Finnish" },
    { value: "French", label: "French" },
    { value: "German", label: "German" },
    { value: "Greek", label: "Greek" },
    { value: "Indonesian", label: "Indonesian" },
    { value: "Italian", label: "Italian" },
    { value: "Japanese", label: "Japanese" },
    { value: "Latin", label: "Latin" },
    { value: "Other", label: "Other" },
    { value: "Polish", label: "Polish" },
    { value: "Portuguese", label: "Portuguese" },
    { value: "Romanic", label: "Romanic" },
    { value: "Russian", label: "Russian" },
    { value: "Scandinavian", label: "Scandinavian" },
    { value: "Slavic", label: "Slavic" },
    { value: "Spanish", label: "Spanish" },
    { value: "Turkish", label: "Turkish" },
    { value: "Yiddish", label: "Yiddish" }
];


export const courseTypes = [
    { value: "", label: "-- Course Type --" },
    { value: "Bachelor", label: "Bachelor" },
    { value: "Church Exam", label: "Church Exam" },
    { value: "Diploma", label: "Diploma" },
    { value: "Double Degree", label: "Double Degree" },
    { value: "LA", label: "LA" },
    { value: "Masters", label: "Masters" },
    { value: "Other", label: "Other" },
    { value: "PHP / Doctorate", label: "PHP / Doctorate" },
    { value: "State Exam", label: "State Exam" }
];


export const numberOfItems = [
    { value: 5, label: "5" },
    { value: 10, label: "10" },
    { value: 20, label: "20" },
    { value: 50, label: "50" },
    { value: 100, label: "100" }
];

export const sortPrograms = [
    { value: "", label: "-- Sort --" },
    { value: "WorldRanking", label: "World Ranking Ascending" },
    { value: "GermanRanking", label: "German Ranking Ascending" },
    { value: "TuitionFee", label: "Tuition Fee Ascending" },
    { value: "TuitionFeeDescending", label: "Tuition Fee Descending" },
]
